### ISSUE TITLE
file clang bug on scaling problem with fold-expressions

### ISSUE THREAD

**Issue by zygoloid** [mattbierner/Super-Template-Tetris#1]
At https://github.com/mattbierner/Super-Template-Tetris/blob/master/tetris/main.cpp#L16, some kind of problem is observed with large _fold-expression_s in Clang. It'd be great if you could file a [bug report](http://llvm.org/bugs) on that issue (or if not, give me some steps to reproduce it and I'll file it for you).

(Sorry, couldn't find another way to get in touch...)

**Comment by mattbierner** [comment]
Thanks, I filed clang bug 23919: https://llvm.org/bugs/show_bug.cgi?id=23919

Seems to be a problem for folds over around 1200 elements.
