### ISSUE TITLE
Satan has rised

### ISSUE THREAD

**Issue by clrnd** [mattbierner/Super-Template-Tetris#2]
he has.

**Comment by mattbierner** [comment]
Look, I'm fine with Satan rising and all, but it's been like ten months! What the hell is taking him so damn long?

If anyone is in contact with Satan, tell him to catch an Uber on up here and start [apocalypsing already](https://en.wikipedia.org/wiki/List_of_dates_predicted_for_apocalyptic_events#Past_predictions)! I'd really like to resolve this issue.

**Comment by ceppix** [comment]
<p align="center">
Please allow me to introduce myself<br>
I'm a language of class and state<br>
I've been around for a long, long year<br>
Stole many a man's soul and faith<br>
</p>

<p align="center">
I was 'round when <a href="https://en.wikipedia.org/wiki/Rust_(programming_language)">Graydon Hoare</a><br>
Had his moment of rusty pain<br>
Made damn sure that <a href="https://en.wikipedia.org/wiki/James_Gosling">Gosling</a><br>
collected garbage and sealed Java's fate<br>
</p>

<p align="center">
Pleased to meet you<br>
Hope you guess my name<br>
But what's puzzling you<br>
Is the nature of my fame<br>
</p>

<p align="center">
I stuck around Bell Labs<br>
When I saw it was a time for a change<br>
Killed old C and its acolytes<br>
While Ritchie screamed in vain<br>
</p>

<p align="center">
I templated struct<br>
watched programmers ruck<br>
As the 90s raged<br>
And the Dot-coms sucked<br>
</p>

<p align="center">
Pleased to meet you<br>
Hope you guess my name, oh yeah!<br>
Ah, what's puzzling you<br>
Is the nature of my fame<br>
</p>

<p align="center">
I watched with glee<br>
While their standard committees <br>
Fought for three decades<br>
For the god they made<br>
</p>

<p align="center">
I shouted out,<br>
"Who killed Concepts?"<br>
When after all<br>
It was <a href="http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2009/n2906.pdf">N2906</a><br>
</p>

<p align="center">
Let me please introduce myself<br>
I'm a language of class and state<br>
And I tossed syntax errors at freshmen<br>
made 'em switch to business major<br>
</p>

<p align="center">
Pleased to meet you<br>
Hope you guessed my name, oh yeah<br>
But what's puzzling you<br>
Is the nature of my fame<br>
</p>

<p align="center">
Oh yeah, SFINAE!
</p>

<p align="center">
Pleased to meet you<br>
Hope you guessed my name<br>
</p>

<p align="center">
Oh yeah!
</p>

<p align="center">
But what's confusing you<br>
Is just the nature of my fame<br>
</p>

<p align="center">
Just as every programmer is an amateur<br>
Or so we can infer<br>
As templates are Turing complete<br>
Just call me old Uncle Ceppix<br>
Cause I like to stay discreet<br>
</p>

<p align="center">
So if you ever use me<br>
Have some courtesy<br>
Have some sympathy, and use some constraint<br>
Follow all the <a href="https://github.com/isocpp/CppCoreGuidelines">
core guidelines</a><br>
Or I'll lay your program to waste
</p>

<p align="center">
Pleased to meet you<br>
Hope you guessed my name<br>
</p>

<p align="center">
Mm yeah!
</p>

<p align="center">
But what's puzzling you<br>
Is the nature of my fame<br>
</p>

<p align="center">
SFINAE!
</p>

<p align="center">
Woo, who<br>
Oh yeah, CRTP it up!<br>
Oh yeah!<br>
Oh yeah!<br>
</p>

<p align="center">
Tell me, what's my name?<br>
Tell me, user, can ya guess my name?<br>
Tell me, sudoer, what's my name?<br>
I tell you one time, you're to <samp>git blame</samp><br>
</p>

<p align="center">
Ooo, who<br>
Ooo, who<br>
Ooo, who<br>
Ooo, who, who<br>
Ooo, who, who<br>
Ooo, who, who<br>
Ooo, who, who<br>
</p>

<p align="center">
Oh, yeah<br>
What's my name?<br>
Tell me: <samp>$ what's my name?</samp><br>
Tell me: <samp>$ sudo what's my name?</samp><br>
</p>

<p align="center">
Ooo, who, who<br>
Ooo, who, who<br>
Ooo, who, who<br>
Ooo, who, who<br>
Ooo, who, who<br>
Ooo, who, who<br>
Ooo, who, who<br>
</p>

<p align="center">
Oh, yeah!
</p>
