### ISSUE TITLE
where is the current_game.h | OS X

### ISSUE THREAD

**Issue by nyotis** [mattbierner/Super-Template-Tetris#3]
I try to build the stt tetris.xcodeproj and i get fatal error: 'current_game.h' file not found

**Comment by mattbierner** [comment]
You have to run reset.sh the first time. That copies new_game.h to current_game.h. I added current_game.h to the gitignore file so it is never uploaded.

**Comment by nyotis** [comment]
OK

**Comment by nyotis** [comment]
current_game.h is _crazy_ ;-)
