### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by estan** [mattbierner/Super-Template-Tetris#4]
Fine piece of Tetris. Great game play. Totally next gen graphics.

I like the write-up as well. Since I couldn't find your e-mail, here's a few nitpicks:

```
The Tetris playfield also just a buffer
```

"is also just a buffer" ?

```
For practical purposes, we'll store dangerzone area of the playfield in the top four pixels.
```

"fourty" or "10 x 4"? (since it's an area).

```
And Runtime, like Satan, will not descend to [evaluation] hell till he has dragged a living part of [compiletime] heaven down with, and helmeted himself with it.
```

"down with him"?

Even though I walk through the darkest valley, I will fear no Runtime, for you are with me; your rod and your staff, they comfort me.

**Comment by mattbierner** [comment]
Thanks, should all be fixed now.
